In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 


In [2]:
data = pd.read_csv('Maternal Health.csv')

In [3]:
df = pd.DataFrame(data)

In [4]:
df.head()

Age  SystolicBP  DiastolicBP    BS  BodyTemp  HeartRate  RiskLevel
0   25         130           80  15.0      98.0         86  high risk
1   35         140           90  13.0      98.0         70  high risk
2   29          90           70   8.0     100.0         80  high risk
3   30         140           85   7.0      98.0         70  high risk
4   35         120           60   6.1      98.0         76   low risk

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1014 entries, 0 to 1013
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          1014 non-null   int64  
 1   SystolicBP   1014 non-null   int64  
 2   DiastolicBP  1014 non-null   int64  
 3   BS           1014 non-null   float64
 4   BodyTemp     1014 non-null   float64
 5   HeartRate    1014 non-null   int64  
 6   RiskLevel    1014 non-null   object 
dtypes: float64(2), int64(4), object(1)
memory usage: 55.6+ KB


In [6]:
df.describe()

Age   SystolicBP  DiastolicBP           BS     BodyTemp  \
count  1014.000000  1014.000000  1014.000000  1014.000000  1014.000000   
mean     29.871795   113.198225    76.460552     8.725986    98.665089   
std      13.474386    18.403913    13.885796     3.293532     1.371384   
min      10.000000    70.000000    49.000000     6.000000    98.000000   
25%      19.000000   100.000000    65.000000     6.900000    98.000000   
50%      26.000000   120.000000    80.000000     7.500000    98.000000   
75%      39.000000   120.000000    90.000000     8.000000    98.000000   
max      70.000000   160.000000   100.000000    19.000000   103.000000   

         HeartRate  
count  1014.000000  
mean     74.301775  
std       8.088702  
min       7.000000  
25%      70.000000  
50%      76.000000  
75%      80.000000  
max      90.000000

In [8]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=20, random_state=42)

In [11]:
classifier=LogisticRegression()

In [12]:
classifier.fit(X_train,y_train)

C:\Users\91932\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [13]:
classifier.predict_proba(X_test)

array([[0.19974178, 0.20025854, 0.59999968],
       [0.92737249, 0.00422748, 0.06840003],
       [0.90815245, 0.00333222, 0.08851534],
       [0.14432241, 0.5341116 , 0.32156598],
       [0.18051623, 0.40823864, 0.41124513],
       [0.14434158, 0.44343144, 0.41222698],
       [0.15784399, 0.38790972, 0.45424629],
       [0.22573454, 0.41133945, 0.36292602],
       [0.08059031, 0.36063156, 0.55877813],
       [0.05515377, 0.63942945, 0.30541679],
       [0.85830228, 0.01129591, 0.13040181],
       [0.07314008, 0.60700017, 0.31985975],
       [0.24492195, 0.33430942, 0.42076863],
       [0.0305387 , 0.70119825, 0.26826306],
       [0.1011992 , 0.33211472, 0.56668608],
       [0.05094243, 0.69218946, 0.25686811],
       [0.35317511, 0.28885193, 0.35797296],
       [0.12311906, 0.7003787 , 0.17650224],
       [0.02438794, 0.6425962 , 0.33301586],
       [0.18484795, 0.2149366 , 0.60021545]])

In [14]:
## Prediction
y_pred=classifier.predict(X_test)

In [15]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [16]:
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[3 0 0]
 [3 2 4]
 [1 2 5]]
0.5
              precision    recall  f1-score   support

   high risk       0.43      1.00      0.60         3
    low risk       0.50      0.22      0.31         9
    mid risk       0.56      0.62      0.59         8

    accuracy                           0.50        20
   macro avg       0.49      0.62      0.50        20
weighted avg       0.51      0.50      0.46        20



In [17]:
## Gridsearchcv
from sklearn.model_selection import GridSearchCV
import warnings
warnings.filterwarnings('ignore')

In [18]:
parameters={'penalty':('l1','l2','elasticnet',None),'C':[1,10,20]}

In [19]:
clf=GridSearchCV(classifier,param_grid=parameters,cv=5)

In [20]:
## Splitting of Train data to validation data
clf.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [1, 10, 20],
                         'penalty': ('l1', 'l2', 'elasticnet', None)})

In [21]:
clf.best_params_

{'C': 10, 'penalty': 'l2'}

In [22]:
classifier=LogisticRegression(C=1,penalty='l2')

In [23]:
classifier.fit(X_train,y_train)

LogisticRegression(C=1)

In [24]:
## Prediction
y_pred=classifier.predict(X_test)
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[3 0 0]
 [3 2 4]
 [1 2 5]]
0.5
              precision    recall  f1-score   support

   high risk       0.43      1.00      0.60         3
    low risk       0.50      0.22      0.31         9
    mid risk       0.56      0.62      0.59         8

    accuracy                           0.50        20
   macro avg       0.49      0.62      0.50        20
weighted avg       0.51      0.50      0.46        20



In [25]:
# make a prediction with a multinomial logistic regression model
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
# define dataset
X, y = make_classification(n_samples=1000, n_features=10, n_informative=5, n_redundant=5, n_classes=3, random_state=1)

In [26]:
# define the multinomial logistic regression model For multiclass classification
model = LogisticRegression(multi_class='ovr', solver='lbfgs')

In [27]:
# Train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [28]:
# trianing model
model.fit(X_train,y_train)

LogisticRegression(multi_class='ovr')

In [29]:
y_pred=model.predict(X_test)

In [30]:
model.predict_proba(X_test)

array([[9.10622335e-02, 5.88916888e-01, 3.20020878e-01],
       [7.74864218e-02, 8.83936419e-01, 3.85771592e-02],
       [6.84414416e-01, 2.03496841e-01, 1.12088744e-01],
       [1.43095699e-02, 9.01488946e-02, 8.95541536e-01],
       [6.87497205e-02, 8.36642893e-01, 9.46073865e-02],
       [1.09007702e-01, 3.07621844e-01, 5.83370453e-01],
       [3.78594000e-01, 2.08265604e-01, 4.13140396e-01],
       [3.14084906e-01, 1.75940674e-01, 5.09974420e-01],
       [5.14671931e-01, 1.90311178e-01, 2.95016891e-01],
       [5.97817613e-01, 3.02410459e-01, 9.97719283e-02],
       [4.20115939e-02, 3.31570100e-01, 6.26418306e-01],
       [4.86740270e-01, 1.04804858e-01, 4.08454873e-01],
       [8.01115911e-01, 3.37497449e-02, 1.65134344e-01],
       [8.98140961e-02, 6.97976196e-01, 2.12209707e-01],
       [7.29023255e-02, 8.39105805e-01, 8.79918698e-02],
       [5.10619176e-01, 2.09225440e-01, 2.80155384e-01],
       [1.24309039e-01, 7.90819633e-01, 8.48713286e-02],
       [3.42847759e-03, 3.71703

In [31]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_pred,y_test))
print(accuracy_score(y_pred,y_test))
print(classification_report(y_pred,y_test))

[[56 10 17]
 [16 41  6]
 [ 3 13 38]]
0.675
              precision    recall  f1-score   support

           0       0.75      0.67      0.71        83
           1       0.64      0.65      0.65        63
           2       0.62      0.70      0.66        54

    accuracy                           0.68       200
   macro avg       0.67      0.68      0.67       200
weighted avg       0.68      0.68      0.68       200

